apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: nginx-secure
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`nginx.home-lab.begoodguys.ovh`)
      kind: Rule
      services:
        - name: nginx
          port: 80
  tls:
    secretName: home-lab-nginx-cert-production