apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: home-lab-nginx-cert-production
  namespace: default
spec:
  commonName: nginx.home-lab.begoodguys.ovh
  secretName: home-lab-nginx-cert-production
  dnsNames:
    - nginx.home-lab.begoodguys.ovh
  issuerRef:
    kind: Issuer
    name: letsencrypt-production