apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: home-lab-qbittorrent-cert-production
  namespace: default
spec:
  commonName: qbittorrent.home-lab.begoodguys.ovh
  secretName: home-lab-qbittorrent-cert-production
  dnsNames:
    - qbittorrent.home-lab.begoodguys.ovh
  issuerRef:
    kind: Issuer
    name: letsencrypt-production