apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: letsencrypt-production
spec:
  acme:
    email: bounteous17@protonmail.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-issuer-home-lab-production
    solvers:
      - http01:
          ingress:
            serviceType: ClusterIP
            ingressClassName: traefik